# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "c8717906a421013fbf5c47e976637862"
application_url = "https://example.com"
embedded = true
name = "Smiffys Promotion Engine"

[access_scopes]
scopes = "read_customers,read_discounts,read_products,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
